### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by dm-17** [UndeadSec/EvilURL#3]
Using latest release "v2.0" (just synced with git)
  

> Insert name: google

> Insert level domain: .com
Traceback (most recent call last):
  File "./evilurl.py", line 259, in <module>
    Runner()
  File "./evilurl.py", line 249, in Runner
    main()
  File "./evilurl.py", line 87, in main
    makeEvil('e', names[2], unicodes[2], url.replace('e', '\u0435'), end)
  File "./evilurl.py", line 60, in makeEvil
    print('\n{2}[*] Char replaced: %s\n[*] Using Unicode: %s\n[*] Unicode number: %s\n{0}[*] Evil url: %s%s{1}\n-------------------------------'.format(GREEN, END, YELLOW) % (char, unicd, uninum, newurl, end))
UnicodeEncodeError: 'ascii' codec can't encode character '\u0435' in position 91: ordinal not in range(128)

I'm using Python version: 
Python 3.6.4 (default, Jan 24 2018, 14:41:27)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux

**Comment by dm-17** [comment]
Solved it myself: the following env variable must be set:
PYTHONIOENCODING=utf-8

**Comment by A1S0N** [comment]
Thank you for saying your solution. :+1:
