### ISSUE TITLE
closed after running

### ISSUE THREAD

**Issue by ErfanPY** [UndeadSec/EvilURL#8]
hello ,
thank you for your good code 
😂 no one could detect it 
but if you add a input() at the end it doesn't close until user press enter and we can copy the fake url

**Comment by xatob** [comment]
I'm sorry, what do you mean?

Pada tanggal Sel, 8 Jan 2019 21.16, Erfan <notifications@github.com>
menulis:

**Comment by ErfanPY** [comment]
when you directly open .py files by double clicking on it python operator will run it as .exe file and when the program finish and print the urls python operator close immediately .

**Comment by naryal2580** [comment]
This is a CLI tool, meant to run via terminal or any command line interface. So, you may add it yourself.. Or, use `getch()` instead of `input()`

**Comment by naryal2580** [comment]
Yeah, this should close this issue too..

**Comment by ErfanPY** [comment]
You are right . tnk
